apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
    tty: true
  - name: docker
    image: docker:29.0-dind  # Official; available (API 1.52)
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
      - name: DOCKER_HOST
        value: "tcp://0.0.0.0:2375"  # TCP exposure
    ports:
      - containerPort: 2375
        name: docker-tcp
    tty: true
    livenessProbe:
      exec:
        command: ["docker", "version"]
      initialDelaySeconds: 60
      periodSeconds: 30
  - name: docker-cli
    image: docker:27.3-cli-alpine  # FIXED: Official, confirmed available; API 1.48
    command: ["cat"]
    tty: true
    securityContext:
      privileged: false
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "64Mi"
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      - name: DOCKER_API_VERSION
        value: "1.44"
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
  - name: trivy
    image: aquasec/trivy:0.55.0  # Official; available
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  # - name: sonar-scanner  # Uncomment if needed
  #   ...
  - name: aws
    image: amazon/aws-cli:2.17.31  # Official; available
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        cpu: "250m"
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "128Mi"
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      - name: DOCKER_API_VERSION
        value: "1.44"
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
  # - name: node  # Uncomment if needed
  #   ...
  volumes:
  - name: docker-sock
    emptyDir: {}
  # - name: shared-artifacts  # Optional
  #   emptyDir: {}
