apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
    tty: true
  - name: docker
    image: docker:29.0-dind  # Official; exists on Docker Hub (API 1.52)
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
      - name: DOCKER_HOST
        value: "tcp://0.0.0.0:2375"  # Expose TCP; bind to all interfaces
    ports:
      - containerPort: 2375
        name: docker-tcp
    tty: true
    # Liveness probe for DinD
    livenessProbe:
      exec:
        command: ["docker", "version"]
      initialDelaySeconds: 60
      periodSeconds: 30
  - name: docker-cli
    image: docker:cli-alpine  # Official latest CLI (v27.3.1 as of Nov 2025; API 1.48, compat with v29)
    # Alternative pinned: image: docker:27.3-cli-alpine
    command: ["cat"]  # Keeps container alive
    tty: true
    securityContext:
      privileged: false
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "64Mi"
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"  # Match DinD TCP
      - name: DOCKER_API_VERSION
        value: "1.44"  # Fallback for negotiation
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock  # Unix socket fallback
  - name: trivy
    image: aquasec/trivy:0.55.0  # Official; confirmed available (latest stable Nov 2025)
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
  # - name: sonar-scanner  # Uncomment if using Sonar stage
  #   image: sonarsource/sonar-scanner-cli:latest
  #   command: ["sleep", "infinity"]
  #   tty: true
  #   resources:
  #     limits:
  #       memory: "2Gi"
  #       cpu: "1"
  #     requests:
  #       memory: "1.5Gi"
  #       cpu: "1"
  - name: aws
    image: amazon/aws-cli:2.17.31  # Official; confirmed available (latest Nov 2025)
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        cpu: "250m"
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "128Mi"
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      - name: DOCKER_API_VERSION
        value: "1.44"
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
  # - name: node  # Uncomment if needed
  #   image: node:22-alpine  # Official LTS (confirmed available)
  #   command: ["sleep", "infinity"]
  #   tty: true
  #   resources:
  #     limits:
  #       memory: "512Mi"
  #       cpu: "500m"
  #     requests:
  #       memory: "256Mi"
  #       cpu: "100m"
  volumes:
  - name: docker-sock
    emptyDir: {}  # Shared for DinD socket
  # - name: shared-artifacts  # Optional
  #   emptyDir: {}
