apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "1Gi"
        cpu: "1"
      requests:
        memory: "1Gi"
        cpu: "1"
    tty: true
  - name: docker
    image: docker:29.0-dind  # Confirmed available; API 1.52
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
      - name: DOCKER_HOST
        value: "tcp://0.0.0.0:2375"
    ports:
      - containerPort: 2375
        name: tcp
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
  - name: docker-cli
    image: docker:27.3-cli  # FIXED: Official Debian CLI (v27.3.1; ~150MB, API 1.48) - 100% available
    command: ["cat"]  # Keeps alive
    tty: true
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      - name: DOCKER_API_VERSION
        value: "1.44"  # Ensures compat
    resources:
      limits:
        cpu: "300m"
        memory: "128Mi"
  - name: trivy
    image: aquasec/trivy:0.55.0  # Official; available
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        cpu: "1"
        memory: "1"
      requests:
        cpu: "1"
        memory: "1"
  # - name: sonar-scanner  # Uncomment if needed
  #   ...
  - name: aws
    image: amazon/aws-cli:2.17.31  # Official; available
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        cpu: "250m"
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "128Mi"
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      - name: DOCKER_API_VERSION
        value: "1.44"
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
  # - name: node  # Uncomment if needed
  #   ...
  volumes:
  - name: docker-sock
    emptyDir: {}
  # - name: shared-artifacts  # Optional
  #   emptyDir: {}
