apiVersion: v1
kind: Pod
metadata:
  labels:
    app: eks-agent
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest

  - name: docker
    image: docker:24.0-dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    command:
      - /bin/sh
      - -c
      - |
        dockerd-entrypoint.sh \
          --host=unix:///var/run/docker.sock \
          --host=tcp://0.0.0.0:2375 &
        while true; do sleep 30; done
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
    tty: true

  - name: aws
    image: alpine:latest
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache python3 py3-pip curl unzip docker-cli &&
        pip3 install awscli &&
        while true; do sleep 30; done
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
    tty: true

  - name: trivy
    image: aquasec/trivy:latest
    command: ["sleep", "infinity"]
    tty: true

  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli:latest
    command: ["sleep", "infinity"]
    tty: true

  - name: node
    image: node:20-alpine
    command: ["sleep", "infinity"]
    tty: true

  volumes:
  - name: docker-sock
    emptyDir: {}
