apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    tty: true
  - name: docker-cli
    image: docker:25.0-cli-alpine   # Recommended: latest stable CLI (25.0.x as of Nov 2025)
    # image: docker:24.0-cli-alpine # still works, but 25.0+ is better
    command:
      - cat                     # Keeps container alive (dind alternative)
    tty: true                   # Required with "cat" trick
    securityContext:
      privileged: false         # NEVER run privileged unless you really need it
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "64Mi"
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
      # readOnly: true        # Uncomment if you only need build/pull, not run/rm
  - name: trivy
    image: aquasec/trivy:latest
    command: ["sleep", "infinity"]
    tty: true
  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli:latest
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
      requests:
        memory: "1.5Gi"
        cpu: "1"
  - name: aws
    image: amazon/aws-cli:2.15.40
    securityContext:
      privileged: true
    command:
      - /bin/sh
      - -c
      - |
        yum install -y docker && \
        dockerd-entrypoint.sh & \
        while true; do sleep 30; done
    tty: true
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
  - name: node
    image: node:20-alpine
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
  volumes:
    - name: docker-sock
      emptyDir: {}
