apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    tty: true
  - name: trivy
    image: aquasec/trivy:latest
    command: ["sleep", "infinity"]
    tty: true
  - name: sonar-scanner
    image: sonarsltd/sonar-scanner-cli:5
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
      requests:
        memory: "1.5Gi"
        cpu: "1"
  - name: aws
    image: amazon/aws-cli:latest
    command: ["sleep", "infinity"]
    tty: true
  - name: node
    image: node:20-alpine
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
