apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
  
  - name: docker # The Daemon (DinD) Container
    image: docker:dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    tty: true
    # FIX: Mount the shared emptyDir volume to the standard socket location
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run 

  - name: docker-cli # The Client Container
    # FIX: Upgraded image to ensure API version >= 1.44
    image: docker:24.0-cli 
    command: ["cat"]
    tty: true
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock

  - name: trivy
    image: aquasec/trivy:latest
    command: ["sleep", "infinity"]
    tty: true
  
  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli:latest
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
      requests:
        memory: "1.5Gi"
        cpu: "1"
  
  - name: aws
    # Note: aws container is used for both aws-cli and git commands.
    # Ensure git is available in this image (it is in amazon/aws-cli:2)
    image: amazon/aws-cli:2.15.40
    command: ["cat"]
    tty: true
  
  - name: node
    image: node:20-alpine
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
        
  volumes:
    # This volume facilitates communication between the 'docker' daemon and 'docker-cli' client
    - name: docker-sock
      emptyDir: {}
