# File: kubernetes-pod.yaml  ←  GUARANTEED TO SCHEDULE  (total ~950m CPU request)
apiVersion: v1
kind: Pod
spec:
  containers:
  # 1. Jenkins agent (needs Java + tools)
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "400m"
      requests:
        memory: "384Mi"
        cpu: "250m"          # ↓ reduced – still plenty for Jenkins
    tty: true

  # 2. Docker-in-Docker daemon (v29 – API 1.52)
  - name: docker
    image: docker:29.0-dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
      - name: DOCKER_HOST
        value: "tcp://0.0.0.0:2375"
    ports:
      - containerPort: 2375
        name: tcp
    resources:
      limits:
        cpu: "600m"          # enough for daemon + builds
        memory: "768Mi"
      requests:
        cpu: "300m"          # ↓ reduced safely
        memory: "512Mi"
    tty: true

  # 3. Docker CLI (official, confirmed pullable)
  - name: docker-cli
    image: docker:27.3-cli
    command: ["cat"]
    tty: true
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      - name: DOCKER_API_VERSION
        value: "1.44"
    resources:
      limits:
        cpu: "250m"
        memory: "128Mi"
      requests:
        cpu: "100m"          # ↓ tiny request
        memory: "64Mi"

  # 4. Trivy (only used briefly)
  - name: trivy
    image: aquasec/trivy:0.55.0
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        cpu: "400m"
        memory: "512Mi"
      requests:
        cpu: "100m"          # ↓ was 500m → overkill
        memory: "256Mi"

  # 5. AWS CLI (tiny)
  - name: aws
    image: amazon/aws-cli:2.17.31
    command: ["sleep", "infinity"]
    tty: true
    env:
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      - name: DOCKER_API_VERSION
        value: "1.44"
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"
      requests:
        cpu: "50m"           # ↓ minimal
        memory: "64Mi"
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock

  volumes:
  - name: docker-sock
    emptyDir: {}

# TOTAL CPU REQUEST ≈ 250 + 300 + 100 + 100 + 50 = 800m  → fits easily on 2× t3.medium (2 vCPU each)
