apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    tty: true
  - name: trivy
    image: aquasec/trivy:latest
    command: ["sleep", "infinity"]
    tty: true
  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli:latest
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
      requests:
        memory: "1.5Gi"
        cpu: "1"
  - name: aws
    image: docker:24.0-dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    command:
      - /bin/sh
      - -c
      - |
        apk add --no-cache python3 py3-pip curl unzip &&
        pip3 install awscli &&
        dockerd-entrypoint.sh \
          --host=tcp://127.0.0.1:2375 \
          --host=unix:///var/run/docker.sock
    tty: true
  - name: node
    image: node:20-alpine
    command: ["sleep", "infinity"]
    tty: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "100m"
