apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins  # make sure this SA exists in the namespace with proper permissions
  restartPolicy: Never

  containers:
  # Default Jenkins JNLP agent (required)
  - name: jnlp
    image: jenkins/inbound-agent:latest-jdk11
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "200m"
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

  # Node.js (for building frontend)
  - name: node
    image: node:20-alpine
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "1024Mi"
        cpu: "1000m"
      requests:
        memory: "512Mi"
        cpu: "500m"

  # SonarQube Scanner
  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli:latest
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "1024Mi"
        cpu: "1000m"

  # Trivy vulnerability scanner
  - name: trivy
    image: aquasec/trivy:latest
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "1024Mi"
        cpu: "1000m"
    volumeMounts:
    - name: trivy-cache
      mountPath: /root/.cache/trivy

  # Docker-in-Docker with Docker client (uses host docker daemon via socket)
  - name: docker
    image: docker:27-dind
    command:
    - cat
    tty: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

  # AWS CLI v2 (for ECR login & git push)
  - name: aws
    image: amazon/aws-cli:2.17.17
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"

  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: trivy-cache
    emptyDir: {}
