
pipeline {
    agent {
        kubernetes {
            label 'eks-agent-' + env.BUILD_ID     // unique label every time → forces new template
            inheritFrom ''                        // VERY IMPORTANT: do NOT inherit old template
            yamlFile 'kubernetes-pod.yaml'         // take the YAML from the repo
        }
    }
    tools {
        nodejs 'nodejs'
    }
    environment  {
        SCANNER_HOME=tool 'sonar-scanner'
        AWS_ACCOUNT_ID = credentials('ACCOUNT_ID')
        AWS_ECR_REPO_NAME = credentials('ECR_REPO1')
        AWS_DEFAULT_REGION = 'us-east-1'
        REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"
    }
    stages {
        stage('Cleaning Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git credentialsId: 'GITHUB', url: 'https://github.com/manojbangari/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
            }
        }

        stage('Sonarqube Analysis') {
            steps {
                container('node') {
                    dir('Application-Code/frontend') {
                        withSonarQubeEnv('sonar-server') {
                            sh """
                            \$SCANNER_HOME/bin/sonar-scanner \
                            -Dsonar.projectName=frontend \
                            -Dsonar.projectKey=frontend
                            """
                        }
                    }
                }
            }
        }

        stage('Quality Check') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                }
            }
        }
        stage('Trivy File Scan') {
            steps {
                container('trivy') {
                    dir('Application-Code/frontend') {
                        sh 'trivy fs . > trivyfs.txt'
                    }
                }
            }
        }

        stage("Docker Image Build") {
            steps {
                container('docker') {
                    dir('Application-Code/frontend') {
                        sh 'docker system prune -f'
                        sh 'docker container prune -f'
                        sh 'docker build -t ${AWS_ECR_REPO_NAME} .'
                    }
                }
            }
        }

        stage("ECR Image Pushing") {
            steps {
                container('aws') {
                    sh '''
                    aws ecr get-login-password --region ${AWS_DEFAULT_REGION} \
                    | docker login --username AWS --password-stdin ${REPOSITORY_URI}

                    docker tag ${AWS_ECR_REPO_NAME} \
                    ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}

                    docker push ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage("TRIVY Image Scan") {
            steps {
                container('trivy') {
                    sh 'trivy image ${REPOSITORY_URI}${AWS_ECR_REPO_NAME}:${BUILD_NUMBER} > trivyimage.txt'
                }
            }
        }

        stage('Checkout Code') {
            steps {
                git credentialsId: 'GITHUB',
                    url: 'https://github.com/manojbangari/End-to-End-Kubernetes-Three-Tier-DevSecOps-Project.git'
            }
        }

        stage('Update Deployment file') {
            environment {
                GIT_REPO_NAME = "End-to-End-Kubernetes-Three-Tier-DevSecOps-Project"
                GIT_USER_NAME = "Manoj-Bangari"
            }

            steps {
                container('aws') {
                    dir('Kubernetes-Manifests-file/Frontend') {
                        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                            sh '''
                            git config user.email "manojbangari39@gmail.com"
                            git config user.name "ManojBangari-DevOps"

                            imageTag=$(grep -oP '(?<=frontend:)[^ ]+' deployment.yaml)

                            sed -i "s/${AWS_ECR_REPO_NAME}:${imageTag}/${AWS_ECR_REPO_NAME}:${BUILD_NUMBER}/" deployment.yaml

                            git add deployment.yaml
                            git commit -m "Update deployment Image to version ${BUILD_NUMBER}"
                            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
                            '''
                        }
                    }
                }
            }
        }
    }
}
